version: '3'
services:
    w_web:
        build: .
        container_name: w_web
        working_dir: /var/www/html
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "../:/var/www/html"
        ports:
            - 8300:80
        restart: always
        depends_on:
            - w_php
            - w_db
    w_php:
        build:
            context: .
            dockerfile: DockerfilePhp
        container_name: w_php
        restart: always
        working_dir: "/var/www/html"
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../:/var/www/html"
    w_db:
        build:
            context: .
            dockerfile: DockerPg
        container_name: w_db
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            PGDATA: "/var/lib/postgresql/data"
        volumes:
            - "./data/db/pg:/var/lib/postgresql/data"
        ports:
            - 5300:5432
networks:
    default:
        external:
            name: test
